[files]
extend-exclude = [
	"CHANGELOG.md",
	"jwks.json",
	"/definitions/*/el-salvador-ssf/*",
	"/meltano/transform/models/*/el-salvador-ssf/*",
	"/meltano/transform/macros/el-salvador-ssf/*",
	"/meltano/transform/models/outputs/non-regulatory/*",
	"dev/fake-service-account.json",
	"**/pnpm-lock.yaml",
	"/apps/admin-panel/lib/graphql/generated/mocks.ts",
	"/apps/admin-panel/messages/es.json",
	"/apps/admin-panel/cypress/manuals/*",
	"scripts/reg-report-xml-validation/samples/*",
	"meltano/utilities/generate-es-reports/generate_es_reports/schemas",
]
